# Generated by Django 2.2.11 on 2020-03-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('imagem', models.ImageField(blank=True, default=None, null=True, upload_to='produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('produtos', models.ManyToManyField(default=None, to='loja.Item')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
