# Generated by Django 2.2.11 on 2020-03-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('em_estoque', models.IntegerField()),
                ('valor', models.FloatField()),
                ('img_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='loja.Quantidade', to='loja.Produto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.User'),
        ),
    ]
