# Generated by Django 2.2.11 on 2020-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(to='loja.Item'),
        ),
    ]
