# Generated by Django 2.2.11 on 2020-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200311_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(upload_to='produtos/<django.db.models.fields.AutoField>'),
        ),
    ]
