# Generated by Django 2.2.11 on 2020-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20200311_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='img',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='produtos/<django.db.models.fields.AutoField>'),
        ),
    ]
