# Generated by Django 2.2.11 on 2020-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_compra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
