# Generated by Django 2.2.11 on 2020-03-13 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0005_auto_20200312_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='username',
        ),
        migrations.AddField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
